// ...existing imports...
import java.util.stream.Collectors;

// ...existing code...
    @Transactional
    public CampaignResponse createDraft(CreateCampaignDraftDto dto) {
        // ...existing code...
        Campaign campaign = Campaign.builder()
                // ...existing code...
                .channels(dto.getChannels() != null ? String.join(",", dto.getChannels()) : null)
                // mapear segmentation lista a CSV o JSON simple
                .segmentation(dto.getSegmentation() != null ? String.join(",", dto.getSegmentation()) : null)
                // ...existing code...
                .build();
        // ...existing code...
    }

    @Transactional
    public CampaignResponse updateDraft(Long id, CreateCampaignDraftDto dto) {
        // ...existing code...
        campaign.setChannels(dto.getChannels() != null ? String.join(",", dto.getChannels()) : null);
        campaign.setSegmentation(dto.getSegmentation() != null ? String.join(",", dto.getSegmentation()) : null);
        // ...existing code...
    }
// ...existing code...
